OSUtils = require(OSUtils)
local user = OSUtils.getUserData("username")
local OSversion = OSUtils.OSVersion()

print("              ##                  "..user)
print("              ##                  ______________________________")
print("              ##                  OS: STARLIGHT_OS")
print("      ##    ######    ##          Build: "..OSversion)
print("        ##  ######  ##            ")
print("          ##########              ")
print("      ##################          ")
print("##############################    ")
print("      ##################          ")
print("          ##########              ")
print("        ##  ######  ##            ")
print("      ##    ######    ##          ")
print("              ##                  ")
print("              ##                  ")
print("              ##                  ")