term.write("              ##                  "..User)
term.write("              ##                  -----------------")
term.write("              ##                  OS: Starlight OS ")
term.write("      ##    ######    ##          Version: 1.0.0   ")
term.write("        ##  ######  ##            Host: type, id   ")
term.write("          ##########              ")
term.write("      ##################          ")
term.write("##############################    ")
term.write("      ##################          ")
term.write("          ##########              ")
term.write("        ##  ######  ##            ")
term.write("      ##    ######    ##          ")
term.write("              ##                  ")
term.write("              ##                  ")
term.write("              ##                  ")